#!/usr/common/bin/perl

foreach $filename (@ARGV) {
    open(IN, $filename) || ((warn "can't process $filename: $!\n"), next);    
    open(OUT, ">${filename}.out") || ((warn "can't process $filename: $!\n"), next);    
    while (<IN>) {
	s/\bstderr\b/STDMSG/g;
	print OUT $_;
    }
    close IN;
    close OUT;
    system "/bin/mv ${filename}.out $filename";
}






