CC = g++
#OPTFLAG = -O3
OPTFLAG = -O2 -fnonnull-objects -fconserve-space 
#OPTFLAG = -g
CFLAGS=$(OPTFLAG) $(PROFFLAG) $(INCLUDE)
LIBS = -lm

.SUFFIXES: .o .cpp .c

OBJS = compact.o input.o stack.o ur.o

.cpp.o:
	$(CC) $(CFLAGS) -c $< 


all: $(OBJS)

compact.o: compact.cpp tab.h stack.h

input.o: input.cpp tab.h stack.h

ur.o:	ur.cpp tab.h stack.h

stack.o: stack.cpp stack.h

clean: 
	-/bin/rm -f  *.o
