CCFLAGS = -g2 -O2 -fconserve-space -fnonnull-objects -Wall

# try -lfl if -ll doesn't work
PFLAGS = -ll
ifeq ($(OSTYPE), linux)
  PFLAGS = -lfl
endif
ifeq ($(OSTYPE), cygwin)
  PFLAGS = -lfl
endif
ifeq ($(OSTYPE), posix)
  PFLAGS = -lfl
endif

#BBFLAGS = -DBBCTRL
BBFLAGS = -DBBCTRL -DBBLEARN
#CC = gcc -g2 -Wall -O2
#CC = gcc -g2
CC = g++ $(BBFLAGS) $(CCFLAGS)
V = 4.0
# SHELL = /bin/ksh

.SUFFIXES: .o .cpp .c

OBJS = bbpddl.tab.o lex.yy.o graphplan.o utilities.o hash.o planner.o dummy.o graph2wff.o control.o justify.o tim.o learn.o verify.o bbio.o sat_solver.o

blackbox: $(OBJS)
	cd compact; make
	cd satz-rand; make
	cd walksat; make
	cd rel_sat_r; make
	cd zchaff; make
	$(CC) compact/*.o satz-rand/*.o walksat/*.o rel_sat_r/*.o $(OBJS) $(PFLAGS) zchaff/libsat.a -lm -o $@ 

simpleblackbox: $(OBJS)
	$(CC) $(OBJS) -ll -o blackbox
#graphplan: y.tab.o lex.yy.o graphplan.o utilities.o hash.o planner.o dummy.o
#	$(CC) lex.yy.o y.tab.o hash.o utilities.o graphplan.o planner.o dummy.o -o graphplan

all:
	make clean; make; make install; make clean

y.tab.o: y.tab.h graphplan.h 

graph2wff.o: graphplan.h interface.h

hash.o: graphplan.h

graphplan.o: graphplan.h interface.h graphplan.cpp
	$(CC) -c -DVERSION=\"$(V)\" graphplan.cpp

utilities.o: graphplan.h

planner.o: graphplan.h interface.h

justify.o: justify.h graphplan.h

tim.o: tim.h graphplan.h

learn.o: tim.h learn.h graphplan.h

bbio.o: learn.h graphplan.h

verify.o: verify.h learn.h graphplan.h

sat_solver.o: sat_solver.cpp
	$(CC) -c sat_solver.cpp

lex.yy.cpp: bbpddl.l
	flex -olex.yy.cpp bbpddl.l 

bbpddl.tab.cpp: bbpddl.y lex.yy.cpp
	bison -d bbpddl.y -o bbpddl.tab.cpp

lex.yy.o: graphplan.h bbpddl.tab.cpp.h control.h lex.yy.cpp

bbpddl.tab.o: graphplan.h control.h


.cpp.o:
	$(CC) $(CFLAGS) -c $< 


install: blackbox
	cp blackbox $(HOME)/bin/`cputype`/blackbox
	cp extract $(HOME)/bin/`cputype`
	cp Run-bb $(HOME)/bin/`cputype`

clean:
	rm -f *.o blackbox
	cd satz-rand; make clean
	cd walksat; make clean
	cd compact; make clean
	cd rel_sat_r; make clean
	cd zchaff; make clean

dist:
	D=`pwd`; cd ..; rm -f blackbox*.tar*; tar cvof blackbox$(V).tar $${D##*/}; compress blackbox$(V).tar; uuencode blackbox$(V).tar.Z blackbox$(V).tar.Z > blackbox$(V)_tar_Z.uu ; rm blackbox$(V).tar.Z

everything:
	make clean; make; make install; make clean; cleanup; make dist

