
CC	=	g++
LINK	=	g++
CFLAGS	=	-g -pedantic -Wall
LFLAGS	=	${CFLAGS}

.PHONY: test clean 

test: hash_test.exe regression_tests.exe
	./hash_test.exe
	./regression_tests.exe
	echo "All tests passed."

clean:
	rm -f hash_test.exe regression_tests.exe *.o *~

%.o : %.cc
	$(CC) $(CFLAGS) -c $< -o $@

%.o : %.cpp
	$(CC) $(CFLAGS) -c $< -o $@

hash_test.exe : hash_test.o
	${LINK} ${LFLAGS} hash_test.o -o hash_test.exe

regression_tests.exe : regression_tests.o regress_1.o
	${LINK} ${LFLAGS} regression_tests.o regress_1.o \
	-o regression_tests.exe