#!/bin/bash

for d in logistics-strips-length prodigy-bw-length bulldozer fridge-typed woodshop
do
    echo "Directory $d"
    cd $d
    for p in *.pddl
    do
	if [ $p != domain.pddl ];
	then
    	    blackbox -o domain.pddl -f $p
	fi
    done
    cd ..
done

